### ISSUE TITLE
Feature request: Context menu (right click)

### ISSUE THREAD

**Issue by binaryfire** [wopehq/wowerlay#54]
Great package!

Would it be possible to add a context menu (right click) option similar to https://atomiks.github.io/tippyjs/v6/misc/ ?

**Comment by kadiryazici** [comment]
I already use it as context menu in my own project :) Wowerlay is a low-level api for popovers. You can give a `VirtualTarget` as target. 

https://floating-ui.com/docs/virtual-elements

on right click you can store position of mouse and show the popover.

For example in my project:

https://github.com/wopehq/wowerlay/assets/47540799/f4dc8e2f-061b-498b-ae49-5b2019e69a6d

https://github.com/Gitification-App/gitification/blob/main/src/pages/HomePage.vue#L278

**Comment by binaryfire** [comment]
@kadiryazici Thanks! Will check this out
