### ISSUE TITLE
Losing the focus

### ISSUE THREAD

**Issue by YanaNychyporovych** [wopehq/wowerlay#55]
What trigger using for Wowerlay (maybe focus)? Is it possible to change the trigger? I show the modal window from the Wowerlay popover, and when I click on a modal window than popover and modal window hide. 
I'll appreciate for helping!

**Comment by kadiryazici** [comment]
Hi, Wowerlay is a low level popover api and you are responsible for triggers. Only trigger built-in for wowerlay is click listener on window to close popover. I am also thinking to add a prop to disable that.

You can build a wrapper `Popover` component and add a click or focus listener to element then set `visible.value = true`

You can see an example in the following link: https://github.com/Gitification-App/gitification/blob/main/src/components/Popover.vue
